version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install --upgrade --force-reinstall . "awscli"
      - pip3 install --upgrade --force-reinstall "protobuf==3.20.0" . "sagemaker" "aws-sam-cli==1.46.0" "aws-lambda-builders==1.14.0" "aws-sam-translator==1.45.0"

  build:
    commands:
      - bash codebuild/build.sh

artifacts:
  files:
    - aws_cloudformation/master_stack.yaml
    - $OUTPUT_CONF_JSON
