Description: Template que cria recursos principais utilizados pela arquitetura

Parameters:
  Stage:
    Type: "String"
    Description: "Application Environment"
    AllowedValues: ["dev", "stg", "prd"]
  S3Bucket:
    Type: "String"
    Description: "S3 Bucket where the deployment artifacts are stored"
  ResultsUpdaterLambdaRole:
    Type: "String"
    Description: "Role to be passed to the lambda function responsible for updating the logs after the training pipeline runs"
    AllowedValues: ["dev", "stg", "prd"]
    
Mappings:
  ResourceNames:
    AppPrefix:
      CamelCase: "blackbeltPredictiveMaintenance"
      SnakeCase: "blackbelt_predictive_maintenance"
      PascalCase: "BlackbeltPredictiveMaintenance"
      KebabCase: "blackbelt-predictive-maintenance"

  StageName:
    dev:
      CamelCase: "Dev"
      UpperCase: "DEV"
    stg:
      CamelCase: "Stg"
      UpperCase: "STG"
    prd:
      CamelCase: "Prd"
      UpperCase: "PRD"

  Resources:

    ModelCreationStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${S3Bucket}.s3.amazonaws.com/${CloudFormationTemplatesS3Prefix}/model_creation_stack.yml"
      Parameters:
        Stage: !Ref "Stage"
        ResultsUpdaterLambdaRole: !Ref "ResultsUpdaterLambdaRole"
      Tags: 
        - Key: "Environment"
          Value: !FindInMap [ "StageName", !Ref "Stage", "UpperCase" ]
        - Key: "Monitoring"
          Value: "enabled"
        - Key: "Project"
          Value: !FindInMap [ "ResourceNames", "AppPrefix", "PascalCase" ]


