
Description: AWS CloudFormation template used to create the networking configurations necessary for the API to work

Parameters:
  Stage:
    Type: "String"
    Description: "Application Environment"
    AllowedValues: ["dev", "stg", "prd"]

Mappings:
  ResourceNames:
    AppPrefix:
      CamelCase: "bainMLEngineeringTest"
      SnakeCase: "bain_ml_engineering_test"
      PascalCase: "BainMLEngineeringTest"
      KebabCase: "bain-ml-engineering-test"

  StageName:
    dev:
      CamelCase: "Dev"
      UpperCase: "DEV"
    stg:
      CamelCase: "Stg"
      UpperCase: "STG"
    prd:
      CamelCase: "Prd"
      UpperCase: "PRD"

Resources:
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 
            - "MainVPC${AppStage}"
            - AppStage: !FindInMap [ "StageName", !Ref Stage, "CamelCase" ]

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub 
            - "PrivateSubnet${AppStage}"
            - AppStage: !FindInMap [ "StageName", !Ref Stage, "CamelCase" ]

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Sub 
            - "PrivateSubnet${AppStage}2"
            - AppStage: !FindInMap [ "StageName", !Ref Stage, "CamelCase" ]

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
      Tags:
        - Key: Name
          Value: !Sub 
            - "PrivateRouteTable${AppStage}"
            - AppStage: !FindInMap [ "StageName", !Ref Stage, "CamelCase" ]

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  DynamoVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable

  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable

  SageMakerVPCEndpointApi:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.sagemaker.api
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SageMakerEndpointSecurityGroup

  SageMakerVPCEndpointRuntime:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.sagemaker.runtime
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SageMakerEndpointSecurityGroup

  SecretsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SageMakerEndpointSecurityGroup

  EcrVPCEndpointDocker:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SageMakerEndpointSecurityGroup

  EcrVPCEndpointApi:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SageMakerEndpointSecurityGroup

  LogsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref MainVPC
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SageMakerEndpointSecurityGroup

  SageMakerEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref MainVPC
      GroupDescription: Security group for SageMaker VPC Endpoint
      SecurityGroupIngress:
        - IpProtocol: '-1'  
          CidrIp: '0.0.0.0/0' 
      SecurityGroupEgress:
        - IpProtocol: '-1'  
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: !Sub 
            - "SageMakerEndpointSG${AppStage}"
            - AppStage: !FindInMap [ "StageName", !Ref Stage, "CamelCase" ]

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value: !Ref MainVPC
  PrivateSubnetId:
    Description: The ID of the private subnet
    Value: !Ref PrivateSubnet
  PrivateSubnetId2:
    Description: The ID of the second private subnet
    Value: !Ref PrivateSubnet2
  SageMakerEndpointSecurityGroupId:
    Description: The ID of the SageMaker endpoint security group
    Value: !Ref SageMakerEndpointSecurityGroup
